[workspace]
members = ["cuda", "cublas", "nccl", "search-cuda-tools", "search-corex-tools"]
resolver = "3"
package.edition = "2024"

[workspace.dependencies]
bindgen = "0.71"
build-script-cfg = "0.1"
find_cuda_helper = "0.2"
